export const LAST_ERROR_MESSAGE_MAX_CHARS = 2_000
export const LAST_ERROR_ARG_MAX_CHARS = 200
export const LAST_ERROR_MAX_ARGS = 32
export const LAST_ERROR_FILE_MAX_BYTES = 16_384
export const LAST_ERROR_SERVER_BASE_URL_MAX_BYTES = 256
